### ISSUE TITLE
Color scale component (Emerson)

### ISSUE THREAD

**Issue by HansKallekleiv** [equinor/webviz-subsurface-components#324] opened 2021-03-23 09:22 UTC
Choose / edit colorscale to use in other component such as the map / intersection component.

**Comment by hkfb** [comment] 2021-06-29 07:09
Duplicate of #297 ?

**Comment by anders-kiaer** [comment] 2021-06-29 08:23
Yes, agree @hkfb. I think this is a duplicate, especially if assuming #297 creates a standalone color scale component.

**Closed by anders-kiaer** 2021-06-29 08:23 UTC
Labels: Emerson
