### ISSUE TITLE
Implement new `@equinor/eds-icons` in map component

### ISSUE THREAD

**Issue by shadab-skhan** [equinor/webviz-subsurface-components#568] opened 2021-09-20 06:21 UTC
Include the following icons in '@equinor/eds-icons' module for layer settings FAB (floating action button):
1. Wells - for actions on wells component
2. Fault polygons - for action on fault polygons displayed on map
3. Surface map - for action on surface component (it's a bitmap image of the surface on deckgl map)
4. Terrain/contour - for action on hill shade component on map (it displays the depth effect on the map thereby depicting hill/terrain)

**Comment by anders-kiaer** [comment] 2021-09-20 06:31
I'm not sure if we will be able to include it in `@equinod/eds-icons`, but we can perhaps as a first step expand on the list in https://github.com/equinor/webviz-subsurface-components/tree/master/react/src/lib/components/VectorSelector/components/images. What do you think @rubenthoms?

**Comment by rubenthoms** [comment] 2021-09-20 07:20
We could make our own package (and Github repo) that works the same way as `@equinor/eds-icons` and can be used with `eds/Icon` (e.g. `@webviz/icons`). That would make it easy to merge it into `@equinor/eds-icons` if that's decided at some point. Expanding the list inside another component does not sound too good. If we decide to have a globally accessible list of icons, we should move all icons to an easier accessible directory. However, I have to admit that I am not a 100% sure about what the actual issue/idea is.

**Comment by anders-kiaer** [comment] 2021-09-23 11:01
> I am not a 100% sure about what the actual issue/idea is.
The use case here is to extend + improve the toolbar in the lower right corner of the map (https://equinor.github.io/webviz-subsurface-components/storybook-static/?path=/story/deckglmap--default). Current state of @shadab-skhan's PR is the picture above, with some non-optimal icons from `eds` wrt. what they should represent. 

The current needed icons is for "hill shading settings" (i.e. the rendering of hill shade effect in the map), "wells layer setting" (settings for the layer of well trajectoris in the map), "fault layer settings" (settings for the faults shown in black lines in the storybook example) and then drawing layer (which I guess have a suitable icon already).

> We could make our own package (and Github repo) that works the same way as @equinor/eds-icons and can be used with eds/Icon (e.g. @webviz/icons). That would make it easy to merge it into @equinor/eds-icons if that's decided at some point.

I agree with you @rubenthoms. Maybe as a first attempt we could try a PR towards https://github.com/equinor/design-system/tree/develop/libraries/static/icons/system-icons, and if that goes stale / is not merged we copy it instead into either a new common folder in `webviz-subsurface-components` or as a new repository (the last option giving some more maintenance work on our side).

**Comment by rubenthoms** [comment] 2021-09-27 07:32
@anders-kiaer how much time would you allow the PR before considering it stale? Should we start including the icons in `wsc` and if the icons are accepted into `EDS` adjust it?

**Comment by anders-kiaer** [comment] 2021-09-27 09:14
@rubenthoms As discussed in today's standup, we could start with a PR towards the `eds/icons` directory, and I can take up contact with `eds` to get their feedback. We'll then as backup plan move the files to `wsc` instead if it turns out to be something not being within `@eds/technical icons` scope for some reason.

**Comment by rubenthoms** [comment] 2021-09-27 10:07
@shadab-skhan @anders-kiaer Here is my first draft of the new icons.
![image](https://user-images.githubusercontent.com/69145689/134888949-f5831711-e189-4d7a-b795-64e5e78e77b8.png)

**Comment by anders-kiaer** [comment] 2021-09-27 10:17
I like it! 👍🤩 In my opinion you could go forward with the suggestions as is @rubenthoms.

(pinging @HansKallekleiv @asnyv @tnatt also for a chance of giving feedback on this).

**Comment by asnyv** [comment] 2021-09-27 10:37
@rubenthoms Overall I think they look good 😊A couple of comments: 
This fault polygon icon is for me more of a fracture than a fault. If you are not familiar with the difference: in a fault a part of the structure is shifted/moved relative to the other part. In a fracture they are just separated (and since the block in the icon is not shifted, it is in my head a fracture). But I'll let the geologists correct me on this @tnatt @HansKallekleiv 😅

The rest I think looks good 👍 the only other concern I may have is whether some of the details in the "Hill shading" are too small when the icon is scaled down to a more common "icon size"? Could be that it still works, but maybe making the mountains that dominates the icon a bit smaller and leave more room for the sun or something? I donno, just a thought... 😊

**Comment by asnyv** [comment] 2021-09-27 11:05
Just as a reference I tried to draw a very quick and dirty example of what I think of when I think a simple "fault" (though this doesn't have much relevance for the "polygon" part...). Attempted a shape and scale which is maybe possible to get into the same style as the other layer icons. But I'm the first to admit that I'm a very bad graphical designer 😅
![image](https://user-images.githubusercontent.com/47146384/134896614-7365030d-f21a-46aa-9170-20e0ca025c9f.png)

**Comment by rubenthoms** [comment] 2021-09-27 11:56
Thanks for valuable input, @asnyv. Here is a new draft based on your suggestions. 

![image](https://user-images.githubusercontent.com/69145689/134903360-571d0658-3974-49b4-87d2-2e419c87272d.png)

**Comment by asnyv** [comment] 2021-09-27 12:30
I like @rubenthoms  😊👍

**Comment by tnatt** [comment] 2021-09-28 08:07
Sorry, a bit late reply from me.. but as a geologist I agree with @asnyv regarding the fault. And very much like the latest draft @rubenthoms 😃

**Comment by anders-kiaer** [comment] 2021-09-28 09:03
Input from Emerson: On the well layer icon, maybe we should remove the "pump" and keep e.g. only the "rig"/"framework"?

**Comment by asnyv** [comment] 2021-09-28 09:32
Pros and cons. I think the pump-jack is something that a lot of people associate with a well, and something that quite clearly distinguishes the icon from anything else. 
On the other hand: Most wells (and none of the wells in Norway) have pump-jacks... 
But the rig/framework is also just the rig used for drilling, and not the well in itself, and a rig of scaffolding is also not unique to wells... So if the pump-jack is not to be used, maybe it should rather be a simple illustration of an actual well? Like a casing or two, with a perforated tubing/lower completion? 
![image](https://user-images.githubusercontent.com/47146384/135061481-c4a318d7-ef88-4962-88b6-31e286dbfa7d.png)
Optionally with e.g. arrows for flow directions if we want to separate producers and injectors
![image](https://user-images.githubusercontent.com/47146384/135061850-fe3c385c-e3e8-468a-89da-e315e950d322.png)

Or just one casing for simplicity
![image](https://user-images.githubusercontent.com/47146384/135062024-e858fa46-0b3b-43a6-a7e7-7a74e588b6cf.png)

But the pump-jack is probably more "iconic"?

**Comment by shadab-skhan** [comment] 2021-09-29 06:07
In RMS, we use rig for well icon as shown below, we can use something like that:
![image](https://user-images.githubusercontent.com/9147767/135211225-1e54981a-0019-4ee0-b1bb-f7c531714f34.png)

**Comment by shadab-skhan** [comment] 2021-09-29 06:10
@anders-kiaer @HansKallekleiv Do we need icons for other components like "Well log viewer" and "Intersection view" too? As of now, there is no use case, but it may be required in the future.

**Comment by asnyv** [comment] 2021-10-19 13:05
@rubenthoms 
Suggest that the `Oil well` icon should be named simply `Well`. Could also be water injector (or even producer) or gas injector/producer.

Also: Not sure about the surface / grid layer icons. Think maybe the downwards arrow indicating "layer" should not be blended into the icon itself? Could we rather have a surface hovering above the arrow? (with grid for the grid layer)

**Comment by rubenthoms** [comment] 2021-10-19 13:21
@asnyv the problem with using the chevron is that it takes quite a bit of space leaving too little space for a detailed/recognizable grid layer illustration.

**Comment by asnyv** [comment] 2021-10-19 14:02
I see your point of the one layer vs multiple layers, but it is a layer to put on top (or under) others, so not really that wrong, is it? 

Otherwise we should maybe not have a reference to the chevron at all, which we sort of have in the first suggestions where we have this hard 90 degree angle? e.g. a simple wavy layer with no chevron

Not sure what is best here... But I think the rightmost of your suggestions are the "cleanest".

**Comment by hkfb** [comment] 2021-11-23 14:54
@rubenthoms @anders-kiaer  I think the last suggestion looks good, and I hope we can go forward with it.

**Comment by anders-kiaer** [comment] 2021-11-23 16:06
@hkfb Yes, we had a meeting with @lucasveil the last days. He has improved them further (fault layer icon as example below), and they are now being reviewed by designers (https://github.com/equinor/design-system/issues/1581#issuecomment-973994047). When they are merged, it will be a new release of `eds-icons`. 👍 
![Screenshot 2021-11-19 at 11 45 17](https://user-images.githubusercontent.com/31612826/143060179-61661628-95f5-4964-b664-23f3b053c9fd.png)

**Comment by anders-kiaer** [comment] 2021-12-09 18:42
@shadab-skhan @hkfb There is now a new release of [`@equinor/eds-icons` on npm](https://www.npmjs.com/package/@equinor/eds-icons).

This has the following new icons (among others):
* fault
* grid layer
* grid layers
* surface layer
* well
* hill shading

They can be previewed in the EDS storybook: https://eds-storybook-react.azurewebsites.net/iframe.html?id=icons--preview&viewMode=story#UI%20views.

Only remaining now I guess before we can close this issue is to import the new icons instead of current generic placeholder icons currently used.

**Closed** 2021-12-14 07:59 UTC
Labels: maintenance, map-component
